name: number_trivia
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it:
  # Bloc for state management
  flutter_bloc:
  # Value equality
  equatable:
  # Functional programming thingies
  dartz:
  # Remote API
  internet_connection_checker_plus: ^2.3.0
  http:
  # Local cache
  shared_preferences:

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  bloc_test: ^9.1.7
